name: Terraform aws ec2 deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ue-west-2
      AWS_ROLE_ARM: arn:aws:iam::793163288981:role/GitHubOIDCRole
      TF_VAR_ami_id: ami-04c376b9db51e51bd

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.x

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::793163288981:role/GitHubOIDCRole
          aws-region: eu-west-2

      - name: terraform init
        run: terraform init

      - name: terrafrom validate
        run: terraform validate

      - name: terraform plan
        if: github.event_name == 'pull_request'
        run: terrafrom plan

      - name: terrafrom apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve
